const BUILTIN_QS = [
      { id: 1, t: "love", q: "If I can be completely honest, have I ever loved someone more than they loved me — and did I let them know it?" },
      { id: 2, t: "love", q: "If I can be completely honest, am I staying in this because it's comfortable, or because it's genuinely right?" },
      { id: 3, t: "love", q: "If I can be completely honest, what am I hoping to receive from love that I am not currently giving myself?" },
      { id: 4, t: "love", q: "If I can be completely honest, did I choose my partner for who they are, or who I thought I could change them into?" },
      { id: 5, t: "love", q: "If I can be completely honest, do I actually trust the person I'm with — or am I just afraid of being alone?" },
      { id: 6, t: "love", q: "If I can be completely honest, what's the one thing about my past relationships I'm most afraid will happen again?" },
      { id: 7, t: "love", q: "If I can be completely honest, have I ever stayed in a relationship because leaving felt too much like failing?" },
      { id: 8, t: "love", q: "If I can be completely honest, what kind of love did I grow up watching — and is it something I actually want to repeat?" },
      { id: 9, t: "love", q: "If I can be completely honest, do I confuse intense feelings with deep connection — and has that cost me?" },
      { id: 10, t: "love", q: "If I can be completely honest, have I ever pushed someone away because getting close felt more dangerous than being alone?" },
      { id: 11, t: "love", q: "If I can be completely honest, what would love feel like if I wasn't afraid of it?" },
      { id: 12, t: "love", q: "If I can be completely honest, have I been waiting for someone to choose me in a way I've never quite believed I deserved?" },
      { id: 13, t: "love", q: "If I can be completely honest, do I love the way I want to be loved, or the way I learned love is supposed to look?" },
      { id: 14, t: "love", q: "If I can be completely honest, is there a person I haven't fully let go of — and what is it I'm still holding onto?" },
      { id: 15, t: "love", q: "If I can be completely honest, what would I do differently in love if I wasn't afraid of getting hurt?" },
      { id: 16, t: "love", q: "If I can be completely honest, have I ever ended something good because I didn't trust that it could stay good?" },
      { id: 17, t: "love", q: "If I can be completely honest, do I know what my boundaries are in love — and have I ever actually enforced them?" },
      { id: 18, t: "feelings", q: "If I can be completely honest, what am I feeling right now that I'm trying very hard not to show anyone?" },
      { id: 19, t: "feelings", q: "If I can be completely honest, when was the last time I felt truly safe to fall apart?" },
      { id: 20, t: "feelings", q: "If I can be completely honest, is there a part of myself I am deeply ashamed of — and have I ever told anyone about it?" },
      { id: 21, t: "feelings", q: "If I can be completely honest, what am I most afraid of losing right now — and why does that define so much of my day?" },
      { id: 22, t: "feelings", q: "If I can be completely honest, who am I when I'm pretending to be okay — and how exhausted is that person when I'm actually by myself?" },
      { id: 23, t: "feelings", q: "If I can be completely honest, is what I've been calling sadness actually anger I didn't feel safe enough to express?" },
      { id: 24, t: "feelings", q: "If I can be completely honest, what am I numbing — and what would I have to feel if I stopped?" },
      { id: 25, t: "feelings", q: "If I can be completely honest, do I feel like I have the right to feel the things I actually feel?" },
      { id: 26, t: "feelings", q: "If I can be completely honest, what emotion, if I let it fully in, would completely undo me — and why am I so afraid of that?" },
      { id: 27, t: "feelings", q: "If I can be completely honest, do I sit with my feelings or do I immediately try to fix, explain, or escape them?" },
      { id: 28, t: "feelings", q: "If I can be completely honest, is there a version of me I miss — and what happened to that person?" },
      { id: 29, t: "feelings", q: "If I can be completely honest, what feeling have I been performing instead of actually feeling?" },
      { id: 30, t: "feelings", q: "If I can be completely honest, how long have I been quietly resentful about something I've never brought up?" },
      { id: 31, t: "feelings", q: "If I can be completely honest, what is the feeling underneath my anxiety — and what is it actually about?" },
      { id: 32, t: "feelings", q: "If I can be completely honest, has loneliness been my baseline for so long that being happy feels like a setup?" },
      { id: 33, t: "relationships", q: "If I can be completely honest, which of my friendships right now feels more like work than a relief?" },
      { id: 34, t: "relationships", q: "If I can be completely honest, am I keeping this friend because of who they are today, or because of our shared history?" },
      { id: 35, t: "relationships", q: "If I can be completely honest, what is the thing I've never told my family because I'm afraid it would change everything?" },
      { id: 36, t: "relationships", q: "If I can be completely honest, do I feel understood by the people I spend the most time with — or am I translating myself?" },
      { id: 37, t: "relationships", q: "If I can be completely honest, have I ever forgiven someone because it was easier than holding them accountable — and has it worked out?" },
      { id: 38, t: "relationships", q: "If I can be completely honest, is there someone in my life I've been dishonest with because honesty felt too risky?" },
      { id: 39, t: "relationships", q: "If I can be completely honest, was there a friendship that ended that I still haven't made peace with?" },
      { id: 40, t: "relationships", q: "If I can be completely honest, in which relationships have I been the difficult one — even if I told the story differently?" },
      { id: 41, t: "relationships", q: "If I can be completely honest, do I know how to ask for what I need — or do I wait and hope people figure it out?" },
      { id: 42, t: "relationships", q: "If I can be completely honest, have I outgrown someone I care about, and am I staying out of guilt rather than love?" },
      { id: 43, t: "relationships", q: "If I can be completely honest, do I give more than I receive — and have I ever actually said anything about it?" },
      { id: 44, t: "relationships", q: "If I can be completely honest, is there someone I've never told how much they mean to me, and what's stopping me?" },
      { id: 45, t: "relationships", q: "If I can be completely honest, do I love the people in my life or the idea I've built of them — and is there a difference?" },
      { id: 46, t: "relationships", q: "If I can be completely honest, have I ever tested someone's loyalty or love — and do I know why I do that?" },
      { id: 47, t: "relationships", q: "If I can be completely honest, what would it look like to tell my family exactly who I am without any apology?" },
      { id: 48, t: "relationships", q: "If I can be completely honest, is there a friend I secretly compete with — and what is that competition actually about?" },
      { id: 49, t: "relationships", q: "If I can be completely honest, do I know how to say no without explaining myself away?" },
      { id: 50, t: "relationships", q: "If I can be completely honest, have I ever stayed silent when I should have defended someone I care about?" },
      { id: 51, t: "relationships", q: "If I can be completely honest, do I care more about how my relationships look from the outside than how they feel on the inside?" },
      { id: 52, t: "relationships", q: "If I can be completely honest, am I in any relationship right now out of habit or history rather than genuine choice?" },
      { id: 53, t: "relationships", q: "If I can be completely honest, what is the one thing I wish I could say to someone I can't say it to?" },
      { id: 54, t: "life", q: "If I can be completely honest, is the life I'm building the one I actually want — or the one I thought I should want?" },
      { id: 55, t: "life", q: "If I can be completely honest, which choices in my life have I made for others rather than for myself?" },
      { id: 56, t: "life", q: "If I can be completely honest, what am I avoiding that I know I'd have to face if I slowed down?" },
      { id: 57, t: "life", q: "If I can be completely honest, do I actually know what I value — or have I just been living by inherited values that were never mine?" },
      { id: 58, t: "life", q: "If I can be completely honest, have I accomplished something I thought would change everything — and felt nothing afterward?" },
      { id: 59, t: "life", q: "If I can be completely honest, how much of my life is driven by comparison — and is it making me better or just smaller?" },
      { id: 60, t: "life", q: "If I can be completely honest, is there something I did years ago that I haven't forgiven myself for — and do I know why?" },
      { id: 61, t: "life", q: "If I can be completely honest, am I using being busy to avoid being present — and what would I have to face if I stopped?" },
      { id: 62, t: "life", q: "If I can be completely honest, what am I holding onto that I know I need to put down?" },
      { id: 63, t: "life", q: "If I can be completely honest, what is the most important question I'm not asking myself about my future?" },
      { id: 64, t: "life", q: "If I can be completely honest, do I believe I'm capable of changing my life — or have I quietly settled?" },
      { id: 65, t: "life", q: "If I can be completely honest, what would I do if I wasn't afraid of failing?" },
      { id: 66, t: "life", q: "If I can be completely honest, what is the thing I tell everyone else to do that I am completely failing to do myself?" },
      { id: 67, t: "life", q: "If I can be completely honest, what do I keep saying yes to that I actually want to say no to?" },
      { id: 68, t: "life", q: "If I can be completely honest, what would I do differently if I genuinely believed I deserved a good life?" },
      { id: 69, t: "life", q: "If I can be completely honest, am I more afraid of failing or of succeeding — and do I know which one holds me back more?" },
      { id: 70, t: "life", q: "If I can be completely honest, have I ever truly sat with not knowing what comes next — or do I always need a plan to feel safe?" },
      { id: 71, t: "life", q: "If I can be completely honest, which of my regrets have I reframed as lessons just to survive them — and is the reframe actually true?" },
      { id: 72, t: "life", q: "If I can be completely honest, what external thing have I been chasing to fill something that's actually an inside job?" },
      { id: 73, t: "life", q: "If I can be completely honest, have I ever truly asked myself what I need — not what I should do, but what I actually need?" },
      { id: 74, t: "life", q: "If I can be completely honest, who am I when no one is watching — and do I like that person?" },
      { id: 75, t: "life", q: "If I can be completely honest, what would my life look like if I stopped waiting to feel ready and just began?" },
      { id: 76, t: "love", q: "If I can be completely honest, have I ever mistaken someone's consistency for love — and only noticed when it stopped?" },
      { id: 77, t: "love", q: "If I can be completely honest, do I know how to be alone without feeling lonely — or is my partner just an anchor?" },
      { id: 78, t: "love", q: "If I can be completely honest, what am I most proud of in how I love — and what am I most afraid to name?" },
      { id: 79, t: "love", q: "If I can be completely honest, is there a conversation I've been avoiding because I know it will end the relationship?" },
      { id: 80, t: "love", q: "If I can be completely honest, do I love the person I'm with today, or the person I hope they will become?" },
      { id: 81, t: "love", q: "If I can be completely honest, am I repeating a dynamic in my current relationship that I never actually witnessed growing up?" },
      { id: 82, t: "love", q: "If I can be completely honest, have I ever loved someone while quietly knowing they were wrong for me — and stayed anyway?" },
      { id: 83, t: "love", q: "If I can be completely honest, what do I do when I feel love fading — do I fight for it, or do I quietly let it go?" },
      { id: 84, t: "love", q: "If I can be completely honest, have I ever fallen out of love and pretended I hadn't because the timing felt impossible?" },
      { id: 85, t: "love", q: "If I can be completely honest, what am I most afraid someone would find out about me if they loved me deeply enough?" },
      { id: 86, t: "love", q: "If I can be completely honest, do I rush into love to outrun loneliness — and has it ever worked?" },
      { id: 87, t: "love", q: "If I can be completely honest, have I ever loved someone more in memory than I did when they were actually with me?" },
      { id: 88, t: "love", q: "If I can be completely honest, what pattern in love do I keep repeating that I haven't been honest enough to name?" },
      { id: 89, t: "love", q: "If I can be completely honest, is there someone who loved me well that I walked away from — and do I understand why I did it?" },
      { id: 90, t: "love", q: "If I can be completely honest, do I make myself smaller in relationships to make someone else feel safer?" },
      { id: 91, t: "love", q: "If I can be completely honest, what do I do when I feel rejected — do I move on or do I build a case against them?" },
      { id: 92, t: "love", q: "If I can be completely honest, have I ever used someone to get over someone else — and did it ever really work?" },
      { id: 93, t: "love", q: "If I can be completely honest, do I know how to apologize in love without making it about how I'm actually right?" },
      { id: 94, t: "love", q: "If I can be completely honest, is there something I'm keeping from my partner that I tell my friends — and why?" },
      { id: 95, t: "love", q: "If I can be completely honest, do I believe I am worthy of the kind of love I actually want?" },
      { id: 96, t: "love", q: "If I can be completely honest, what would safe love feel like — and would I even trust it if I found it?" },
      { id: 97, t: "love", q: "If I can be completely honest, have I ever let go of someone too soon because I was afraid of how much I needed them?" },
      { id: 98, t: "love", q: "If I can be completely honest, do I know the difference between being chosen and being settled for — and have I accepted one as the other?" },
      { id: 99, t: "love", q: "If I can be completely honest, have I stayed in love long after the love was gone because being alone felt even more frightening?" },
      { id: 100, t: "love", q: "If I can be completely honest, what would I have to stop pretending in order to be fully honest with someone who loves me?" },
      { id: 101, t: "love", q: "If I can be completely honest, do I believe love is supposed to be hard — and has that belief kept me in things I should have left?" },
      { id: 102, t: "love", q: "If I can be completely honest, what is the kindest thing anyone has ever said to me — and why is it so hard to believe?" },
      { id: 103, t: "love", q: "If I can be completely honest, have I ever felt deeply loved and still felt completely alone at the same time?" },
      { id: 104, t: "love", q: "If I can be completely honest, what do I wish someone would ask me — and why haven't I just said it out loud?" },
      { id: 105, t: "love", q: "If I can be completely honest, is there a love I look back on and think 'that was my only chance' — and is that true?" },
      { id: 106, t: "love", q: "If I can be completely honest, what is the thing about me that makes me hardest to love?" },
      { id: 107, t: "love", q: "If I can be completely honest, what is the most unselfish thing I've ever done for someone I loved?" },
      { id: 108, t: "love", q: "If I can be completely honest, have I ever pretended to care about something because it mattered to the person I loved?" },
      { id: 109, t: "love", q: "If I can be completely honest, do I know what it feels like to just be loved — without needing to fix, perform, or restore the peace?" },
      { id: 110, t: "love", q: "If I can be completely honest, what would it feel like to love someone without any agenda — just because they exist?" },
      { id: 111, t: "love", q: "If I can be completely honest, do I know why I fall for the people I fall for — or have I just been calling it chemistry?" },
      { id: 112, t: "love", q: "If I can be completely honest, is there a heartbreak I've never fully recovered from that I've been pretending is healed?" },
      { id: 113, t: "love", q: "If I can be completely honest, what would I need to forgive in myself before I could truly love someone else without reservation?" },
      { id: 114, t: "love", q: "If I can be completely honest, have I ever held a grudge in love that quietly became the reason everything fell apart?" },
      { id: 115, t: "love", q: "If I can be completely honest, what is the thing about me in love that I am most ashamed of?" },
      { id: 116, t: "love", q: "If I can be completely honest, have I ever felt more alive in the ending of something than in the middle of it?" },
      { id: 117, t: "love", q: "If I can be completely honest, do I believe someone could know everything about me and still want to stay?" },
      { id: 118, t: "love", q: "If I can be completely honest, is there a time I chose convenience over connection — and what did I lose?" },
      { id: 119, t: "love", q: "If I can be completely honest, do I know how to receive love without immediately trying to pay it back?" },
      { id: 120, t: "love", q: "If I can be completely honest, what is the one thing I've never told anyone about what I need in love?" },
      { id: 121, t: "love", q: "If I can be completely honest, have I ever loved someone mostly because of how much they loved me?" },
      { id: 122, t: "love", q: "If I can be completely honest, what is the most loving thing I've ever done that no one will ever know about?" },
      { id: 123, t: "love", q: "If I can be completely honest, what would it take for me to feel completely safe in love?" },
      { id: 124, t: "love", q: "If I can be completely honest, what is the part of love I find hardest — and do I know why?" },
      { id: 125, t: "love", q: "If I can be completely honest, if I could go back to one moment in love and do something differently, what would it be — and why haven't I grieved it properly?" },
      { id: 126, t: "feelings", q: "If I can be completely honest, is there an emotion I was taught was dangerous — and am I still afraid of it?" },
      { id: 127, t: "feelings", q: "If I can be completely honest, when did I first learn to hide what I was feeling — and from whom?" },
      { id: 128, t: "feelings", q: "If I can be completely honest, what does it feel like in my body when I'm not okay — and do I let myself notice?" },
      { id: 129, t: "feelings", q: "If I can be completely honest, have I been labeling overwhelm as laziness for so long that I've started to believe it?" },
      { id: 130, t: "feelings", q: "If I can be completely honest, what feeling do I reach for when I want to avoid feeling the real one?" },
      { id: 131, t: "feelings", q: "If I can be completely honest, is there a part of me that is still grieving something no one else even knows I lost?" },
      { id: 132, t: "feelings", q: "If I can be completely honest, do I feel more comfortable being angry than being sad — and do I know why?" },
      { id: 133, t: "feelings", q: "If I can be completely honest, when was the last time I cried about something that wasn't about me?" },
      { id: 134, t: "feelings", q: "If I can be completely honest, is there a feeling I've been avoiding for years because I don't know how to move through it?" },
      { id: 135, t: "feelings", q: "If I can be completely honest, what emotion makes me feel most like myself — and do I get to feel it often?" },
      { id: 136, t: "feelings", q: "If I can be completely honest, do I ever feel like a spectator in my own life — and what would make me feel like the main character again?" },
      { id: 137, t: "feelings", q: "If I can be completely honest, what feeling has the strongest hold over me right now — and where is it leading me?" },
      { id: 138, t: "feelings", q: "If I can be completely honest, how do I react when someone validates my feelings — or do I immediately find something to diminish it?" },
      { id: 139, t: "feelings", q: "If I can be completely honest, what does hope feel like for me right now — and am I letting myself feel it?" },
      { id: 140, t: "feelings", q: "If I can be completely honest, is there something I feel guilty about that I've never been able to put into words?" },
      { id: 141, t: "feelings", q: "If I can be completely honest, do I know the difference between being tired and being defeated — and which one is this?" },
      { id: 142, t: "feelings", q: "If I can be completely honest, what would it mean to actually feel at peace — not content, not numb, but genuinely at peace?" },
      { id: 143, t: "feelings", q: "If I can be completely honest, have I ever felt joy that I immediately sabotaged because I didn't trust it would last?" },
      { id: 144, t: "feelings", q: "If I can be completely honest, what feeling do I judge in others that I secretly recognize in myself?" },
      { id: 145, t: "feelings", q: "If I can be completely honest, if my body could speak right now, what would it say it has been holding?" },
      { id: 146, t: "relationships", q: "If I can be completely honest, is there a dynamic in one of my relationships that I know isn't healthy but have never named out loud?" },
      { id: 147, t: "relationships", q: "If I can be completely honest, do I let people really know me — or do I offer a curated version and call it closeness?" },
      { id: 148, t: "relationships", q: "If I can be completely honest, is there someone I am holding to a standard I never meet myself?" },
      { id: 149, t: "relationships", q: "If I can be completely honest, have I ever stayed in a friendship because I was afraid of the gossip that would follow the ending?" },
      { id: 150, t: "relationships", q: "If I can be completely honest, what would it take for me to forgive someone who never said they were sorry?" },
      { id: 151, t: "relationships", q: "If I can be completely honest, do I ever use my phone to avoid actually connecting with the people right in front of me?" },
      { id: 152, t: "relationships", q: "If I can be completely honest, is there a relationship in my life that's trying to survive on history alone — and what would I do if we met today?" },
      { id: 153, t: "relationships", q: "If I can be completely honest, have I ever disappeared from someone's life without explanation — and do I know what I was really running from?" },
      { id: 154, t: "relationships", q: "If I can be completely honest, what role do I play in my closest relationships — and did I choose it, or did it just happen to me?" },
      { id: 155, t: "relationships", q: "If I can be completely honest, do I have a relationship where I feel completely free to be myself — and what does that tell me?" },
      { id: 156, t: "relationships", q: "If I can be completely honest, is there someone I've been slowly pulling away from that I haven't been honest with about why?" },
      { id: 157, t: "relationships", q: "If I can be completely honest, do I hold people to standards I've never actually told them about — and then feel let down when they miss them?" },
      { id: 158, t: "relationships", q: "If I can be completely honest, have I ever kept a friendship or relationship alive mostly because ending it felt like admitting something about myself?" },
      { id: 159, t: "relationships", q: "If I can be completely honest, how do I show up when a relationship gets difficult — and is that who I want to be?" },
      { id: 160, t: "relationships", q: "If I can be completely honest, is there a person I love who I've been slowly taking for granted — and what would I feel if they were suddenly gone?" },
      { id: 161, t: "relationships", q: "If I can be completely honest, do I let the people in my life see me when I'm struggling, or do I only show up when I'm strong?" },
      { id: 162, t: "relationships", q: "If I can be completely honest, what is the truest thing about how I treat the people I care about most — even when I'm angry?" },
      { id: 163, t: "relationships", q: "If I can be completely honest, what is the one thing about how my parents raised me that I've never fully forgiven them for?" },
      { id: 164, t: "relationships", q: "If I can be completely honest, what kind of friend am I when my friend is succeeding in a way I'm not?" },
      { id: 165, t: "life", q: "If I can be completely honest, am I living the same year on repeat, calling it stability when it might actually be stagnation?" },
      { id: 166, t: "life", q: "If I can be completely honest, what do I believe I deserve — and is it less than what I would want for the people I love most?" },
      { id: 167, t: "life", q: "If I can be completely honest, is there a version of myself I have given up on that I haven't properly mourned?" },
      { id: 168, t: "life", q: "If I can be completely honest, what does rest feel like for me — and do I believe I have to earn it?" },
      { id: 169, t: "life", q: "If I can be completely honest, what am I pretending not to know — and what would I have to do if I finally admitted I knew it?" },
      { id: 170, t: "life", q: "If I can be completely honest, when did I last do something purely because it brought me joy — with no goal, no outcome, no audience?" },
      { id: 171, t: "life", q: "If I can be completely honest, do I trust myself — and if not, when did I stop, and what happened?" },
      { id: 172, t: "life", q: "If I can be completely honest, is there a chapter of my life I've never let myself fully close — and what is keeping it open?" },
      { id: 173, t: "life", q: "If I can be completely honest, what does courage look like for me right now — not in general, but specifically, today?" },
      { id: 174, t: "life", q: "If I can be completely honest, am I using my goals to avoid facing my reality — and what's the difference?" },
      { id: 175, t: "life", q: "If I can be completely honest, what am I most afraid of being asked — and do I have an answer yet?" },
      { id: 176, t: "life", q: "If I can be completely honest, what did I think would make me happy that hasn't — and what am I still chasing?" },
      { id: 177, t: "life", q: "If I can be completely honest, what would my life look like if I stopped trying to prove myself to everyone else?" },
      { id: 178, t: "love", q: "If I can be completely honest, do I know what it feels like to miss someone for who they are, or have I mostly missed who I was when I was with them?" },
      { id: 179, t: "love", q: "If I can be completely honest, have I ever been so afraid of ruining something that I held back — and did the holding back ruin it anyway?" },
      { id: 180, t: "love", q: "If I can be completely honest, what is the most honest thing I have ever said to someone I loved — and what made that moment possible?" },
      { id: 181, t: "feelings", q: "If I can be completely honest, is there a feeling I only let myself have alone — and what does it say about me that I hide it from everyone else?" },
      { id: 182, t: "feelings", q: "If I can be completely honest, have I been so focused on holding everything together that I have completely lost track of how I actually feel?" },
      { id: 183, t: "feelings", q: "If I can be completely honest, what do I feel when things go quiet — and do I fill the silence before I even find out?" },
      { id: 184, t: "feelings", q: "If I can be completely honest, is there something I am grieving that other people would not consider a real loss — and does their dismissal make it harder to heal?" },
      { id: 185, t: "feelings", q: "If I can be completely honest, when was the last time I felt genuinely lighthearted — and what would it take to feel that way again?" },
      { id: 186, t: "relationships", q: "If I can be completely honest, is there someone in my life I keep forgiving not because I've healed, but because confronting it feels harder than pretending?" },
      { id: 187, t: "relationships", q: "If I can be completely honest, do I show people who I am gradually, or do I decide very early on how much of myself they get to see?" },
      { id: 188, t: "relationships", q: "If I can be completely honest, what am I hiding from my closest friend right now — and what am I afraid would happen if I told them?" },
      { id: 189, t: "relationships", q: "If I can be completely honest, is there a dynamic in my family I have outgrown but still fall back into every time I'm around them?" },
      { id: 190, t: "relationships", q: "If I can be completely honest, what would my relationships feel like if I stopped managing how people see me and just let them see me?" },
      { id: 191, t: "life", q: "If I can be completely honest, what am I tolerating in my daily life that I have stopped noticing — and what has that quiet tolerance cost me?" },
      { id: 192, t: "life", q: "If I can be completely honest, do I actually like who I am becoming, or have I just gotten used to them?" },
      { id: 193, t: "life", q: "If I can be completely honest, is there a decision I keep postponing that I already know the answer to — and what am I protecting myself from by waiting?" },
      { id: 194, t: "life", q: "If I can be completely honest, what would I stop doing immediately if I stopped needing other people's approval to feel like enough?" },
      { id: 195, t: "life", q: "If I can be completely honest, have I confused being needed with being valued — and has that confusion shaped the choices I've made?" },
      { id: 196, t: "life", q: "If I can be completely honest, what is one thing I know I should let go of that I keep picking back up because the weight of it has become familiar?" },
      { id: 197, t: "life", q: "If I can be completely honest, when did I last surprise myself — and what does it mean that I can't easily remember?" },
      { id: 198, t: "life", q: "If I can be completely honest, is the way I spend my time a reflection of what I actually value, or a reflection of what I am afraid to change?" },
      { id: 199, t: "life", q: "If I can be completely honest, have I been waiting for a sign, a moment, or a feeling of certainty that will never actually come — and what would I do if I accepted that?" },
      { id: 200, t: "life", q: "If I can be completely honest, what is the truest, most unguarded thing I could say about my life right now — the thing I have not said to anyone?" },
      { id: 201, t: "love", q: "If I can be completely honest, have I ever mistaken someone's need for me as love — and did I let that become enough?" },
      { id: 202, t: "love", q: "If I can be completely honest, what does the way I argue say about how afraid I am of losing the person I'm arguing with?" },
      { id: 203, t: "love", q: "If I can be completely honest, have I ever loved someone I didn't particularly like — and how did I hold those two things at once?" },
      { id: 204, t: "love", q: "If I can be completely honest, do I know what it feels like to be loved without earning it — and have I ever actually let that in?" },
      { id: 205, t: "love", q: "If I can be completely honest, have I ever used love as a reason to stop growing?" },
      { id: 206, t: "love", q: "If I can be completely honest, is there someone I still haven't forgiven — and is that unforgiveness quietly shaping how I love right now?" },
      { id: 207, t: "love", q: "If I can be completely honest, what is the story I keep telling myself about why I'm hard to love?" },
      { id: 208, t: "love", q: "If I can be completely honest, have I ever chosen someone who couldn't fully love me back because it felt safer than being truly seen?" },
      { id: 209, t: "love", q: "If I can be completely honest, what part of love do I perform rather than feel?" },
      { id: 210, t: "love", q: "If I can be completely honest, do I know how to receive affection — or do I deflect it, minimize it, or feel like I have to immediately give something back?" },
      { id: 211, t: "love", q: "If I can be completely honest, what have I sacrificed for love that I've never admitted I resent?" },
      { id: 212, t: "love", q: "If I can be completely honest, have I ever stayed silent about something that was slowly breaking me — just to keep the peace?" },
      { id: 213, t: "love", q: "If I can be completely honest, do I know the difference between loving someone and needing them?" },
      { id: 214, t: "love", q: "If I can be completely honest, have I ever confused passion with volatility — and called the chaos love?" },
      { id: 215, t: "love", q: "If I can be completely honest, what does the way I love reveal about my deepest fear?" },
      { id: 216, t: "love", q: "If I can be completely honest, is there a version of love I keep chasing that I never actually want to catch?" },
      { id: 217, t: "love", q: "If I can be completely honest, have I ever ended something not because it was wrong, but because I was terrified it might actually be right?" },
      { id: 218, t: "love", q: "If I can be completely honest, what would I need to believe about myself to accept that I deserve consistent, calm love?" },
      { id: 219, t: "love", q: "If I can be completely honest, have I been more committed to the idea of a relationship than to the actual person in it?" },
      { id: 220, t: "love", q: "If I can be completely honest, what do I want from love that I've never said out loud because I was afraid of how it would sound?" },
      { id: 221, t: "love", q: "If I can be completely honest, do I love people fully or do I always hold a little piece of myself back just in case?" },
      { id: 222, t: "love", q: "If I can be completely honest, has the way I've been loved ever made me feel more alone than being alone does?" },
      { id: 223, t: "love", q: "If I can be completely honest, what am I still grieving from a relationship I've pretended to be over?" },
      { id: 224, t: "love", q: "If I can be completely honest, do I love others the way I wish I had been loved — or the way I was actually shown love?" },
      { id: 225, t: "love", q: "If I can be completely honest, have I ever let someone love me poorly because I didn't believe I could ask for better?" },
      { id: 226, t: "love", q: "If I can be completely honest, what recurring pattern in my relationships am I still pretending is a coincidence?" },
      { id: 227, t: "love", q: "If I can be completely honest, have I ever fallen in love with someone's potential and ignored who they actually were?" },
      { id: 228, t: "love", q: "If I can be completely honest, what does love feel like in my body — and when was the last time it felt safe?" },
      { id: 229, t: "love", q: "If I can be completely honest, am I looking for a partner or am I looking for someone to fix something in me?" },
      { id: 230, t: "love", q: "If I can be completely honest, what would I have to give up about my identity if I let love in completely?" },
      { id: 231, t: "love", q: "If I can be completely honest, is there a person I've wronged in love that I've never properly apologized to?" },
      { id: 232, t: "love", q: "If I can be completely honest, do I know what my attachment style is — and am I doing anything about it?" },
      { id: 233, t: "love", q: "If I can be completely honest, have I ever felt more in love with someone after they left than when they were here?" },
      { id: 234, t: "love", q: "If I can be completely honest, what kind of love do I show when things get difficult — and am I proud of that?" },
      { id: 235, t: "love", q: "If I can be completely honest, do I actually want what I say I want in love, or have I just said it for so long I've stopped questioning it?" },
      { id: 236, t: "love", q: "If I can be completely honest, what is the most loving thing I've ever done that I've never told anyone?" },
      { id: 237, t: "love", q: "If I can be completely honest, have I ever withheld love as a form of punishment — and did it feel like control?" },
      { id: 238, t: "love", q: "If I can be completely honest, what would love look like if I designed it entirely around who I actually am, not who I think I should be?" },
      { id: 239, t: "love", q: "If I can be completely honest, is there someone I love that I've been treating carelessly because I assume they'll always be there?" },
      { id: 240, t: "love", q: "If I can be completely honest, have I ever been in love and deeply lonely at the same time — and what did that silence cost me?" },
      { id: 241, t: "love", q: "If I can be completely honest, what's the biggest lie I've ever told someone I loved — and have I made peace with it?" },
      { id: 242, t: "love", q: "If I can be completely honest, do I know how to love without losing myself — and if not, where does the self go?" },
      { id: 243, t: "love", q: "If I can be completely honest, have I ever used someone's love for me as a safety net while I kept one foot out the door?" },
      { id: 244, t: "love", q: "If I can be completely honest, what would it mean for me if love turned out to be simple?" },
      { id: 245, t: "love", q: "If I can be completely honest, is there a goodbye I never got that I'm still waiting for?" },
      { id: 246, t: "love", q: "If I can be completely honest, do I know what I actually need in love — not what sounds good, but what I need to feel at home?" },
      { id: 247, t: "love", q: "If I can be completely honest, have I ever chosen someone who couldn't give me what I needed and then blamed them for it?" },
      { id: 248, t: "love", q: "If I can be completely honest, what does jealousy reveal about what I'm most afraid of losing?" },
      { id: 249, t: "love", q: "If I can be completely honest, have I been searching for someone to make me feel whole — and what happens when they can't?" },
      { id: 250, t: "love", q: "If I can be completely honest, is there love I've walked away from that I still wonder about?" },
      { id: 251, t: "love", q: "If I can be completely honest, what would I tell my younger self about the first person they fell in love with?" },
      { id: 252, t: "love", q: "If I can be completely honest, do I love loudly or quietly — and is that a choice, or a wound?" },
      { id: 253, t: "love", q: "If I can be completely honest, what has loving the wrong person taught me that loving the right person never could?" },
      { id: 254, t: "love", q: "If I can be completely honest, have I ever confused someone's unavailability with mystery — and chased it?" },
      { id: 255, t: "love", q: "If I can be completely honest, what am I afraid would happen if someone truly knew me and loved me anyway?" },
      { id: 256, t: "love", q: "If I can be completely honest, is there a love language I've been asking for that I've never thought to give?" },
      { id: 257, t: "love", q: "If I can be completely honest, do I believe love is supposed to be hard — and where did I learn that?" },
      { id: 258, t: "love", q: "If I can be completely honest, what does it mean that the relationships I've idealized were often the ones where I was most invisible?" },
      { id: 259, t: "love", q: "If I can be completely honest, have I ever let a relationship define my worth — and am I still letting it?" },
      { id: 260, t: "love", q: "If I can be completely honest, what does the person I've loved most deeply reveal about what I value in myself?" },
      { id: 261, t: "love", q: "If I can be completely honest, do I know how to fight fairly in love — or do I go quiet, go big, or go away?" },
      { id: 262, t: "love", q: "If I can be completely honest, is there a romantic chapter of my life I've glamorized in memory but was actually damaging in real time?" },
      { id: 263, t: "love", q: "If I can be completely honest, what does it mean to me that I find it easier to love others than to love myself?" },
      { id: 264, t: "love", q: "If I can be completely honest, have I ever given someone access to me that I later regretted — and what did that teach me about trust?" },
      { id: 265, t: "love", q: "If I can be completely honest, is there someone I need to let go of — not because they're bad, but because holding on is keeping me small?" },
      { id: 266, t: "love", q: "If I can be completely honest, what kind of love do I think I deserve right now, in this season of my life?" },
      { id: 267, t: "love", q: "If I can be completely honest, have I ever been so afraid of being abandoned that I abandoned someone first?" },
      { id: 268, t: "love", q: "If I can be completely honest, what does intimacy feel like for me — and at what point does it start to feel like too much?" },
      { id: 269, t: "love", q: "If I can be completely honest, have I repeated the same relationship with different people — and do I know why?" },
      { id: 270, t: "love", q: "If I can be completely honest, what is the most honest thing I could say about my last heartbreak — beyond the version I tell people?" },
      { id: 271, t: "love", q: "If I can be completely honest, is there something I keep asking for in love that I've never actually been willing to give?" },
      { id: 272, t: "love", q: "If I can be completely honest, do I know what it means to love someone on their worst day — and have I been that kind of love for someone?" },
      { id: 273, t: "love", q: "If I can be completely honest, what would it take for me to believe that this time, love could be different?" },
      { id: 274, t: "love", q: "If I can be completely honest, have I ever punished someone for someone else's mistakes?" },
      { id: 275, t: "love", q: "If I can be completely honest, what does the gap between how I love and how I want to be loved say about me?" },
      { id: 276, t: "love", q: "If I can be completely honest, is there a version of me that I only show up as when I'm in love — and do I miss that person?" },
      { id: 277, t: "love", q: "If I can be completely honest, what do I need to heal before I can be the partner I actually want to be?" },
      { id: 278, t: "love", q: "If I can be completely honest, have I ever been honest with a partner about something that cost me everything — and do I regret it?" },
      { id: 279, t: "love", q: "If I can be completely honest, what is the difference between the love I give and the love I desperately need to receive?" },
      { id: 280, t: "love", q: "If I can be completely honest, is there a moment of connection I let pass because I was too afraid to reach for it?" },
      { id: 281, t: "love", q: "If I can be completely honest, do I know how to be vulnerable without immediately regretting it?" },
      { id: 282, t: "love", q: "If I can be completely honest, have I ever loved someone who didn't make me feel safe — and called that exciting?" },
      { id: 283, t: "love", q: "If I can be completely honest, what does love ask of me that I've been quietly refusing?" },
      { id: 284, t: "love", q: "If I can be completely honest, is the love I'm giving right now the kind I'd be proud of if I looked back on it in ten years?" },
      { id: 285, t: "love", q: "If I can be completely honest, what have I been waiting for someone to say to me that I've never asked for directly?" },
      { id: 286, t: "love", q: "If I can be completely honest, have I ever mistaken longing for love — and built something real on top of something imagined?" },
      { id: 287, t: "love", q: "If I can be completely honest, what would change in my love life if I stopped trying to manage how I am perceived?" },
      { id: 288, t: "love", q: "If I can be completely honest, do I know what it feels like when love is easy — or have I always been working for it?" },
      { id: 289, t: "love", q: "If I can be completely honest, is there something I've never forgiven myself for in love?" },
      { id: 290, t: "love", q: "If I can be completely honest, what did my first real heartbreak teach me that I carry into every relationship since?" },
      { id: 291, t: "love", q: "If I can be completely honest, do I feel lovable — and what would it take to believe it on a regular day, not just when someone reminds me?" },
      { id: 292, t: "love", q: "If I can be completely honest, what is the most selfless thing I've ever done in love — and did anyone ever know?" },
      { id: 293, t: "love", q: "If I can be completely honest, am I in the right relationship for who I am now, or for who I was when it began?" },
      { id: 294, t: "love", q: "If I can be completely honest, what does the love I give when no one is watching say about my character?" },
      { id: 295, t: "love", q: "If I can be completely honest, have I been trying to get someone to love me the way someone else never did?" },
      { id: 296, t: "love", q: "If I can be completely honest, is there a chapter of my love life I've never told anyone the full truth about?" },
      { id: 297, t: "love", q: "If I can be completely honest, what would my relationship look like if both of us said exactly what we needed, right now?" },
      { id: 298, t: "love", q: "If I can be completely honest, have I ever loved someone more after they showed me they were flawed — and what does that reveal?" },
      { id: 299, t: "love", q: "If I can be completely honest, what is the thing about love that still confuses me — the part I thought I'd have figured out by now?" },
      { id: 300, t: "love", q: "If I can be completely honest, what would I want my great love story to say about who I was?" },
      { id: 301, t: "feelings", q: "If I can be completely honest, is there a feeling I've been calling anxiety that is actually excitement I don't feel I deserve?" },
      { id: 302, t: "feelings", q: "If I can be completely honest, what does my body carry that my mind refuses to acknowledge?" },
      { id: 303, t: "feelings", q: "If I can be completely honest, have I ever been so deep in survival mode that I forgot what it felt like to just exist?" },
      { id: 304, t: "feelings", q: "If I can be completely honest, what feeling do I always rush to explain away before anyone can witness it?" },
      { id: 305, t: "feelings", q: "If I can be completely honest, is there a grief I've been carrying alone that deserves to be witnessed?" },
      { id: 306, t: "feelings", q: "If I can be completely honest, what does joy feel like for me — and when was the last time I felt it without immediately bracing for it to end?" },
      { id: 307, t: "feelings", q: "If I can be completely honest, have I ever felt proud of myself and immediately buried it so no one would think I was arrogant?" },
      { id: 308, t: "feelings", q: "If I can be completely honest, what feeling have I been medicating — with food, screens, busyness, or something else — that I haven't named yet?" },
      { id: 309, t: "feelings", q: "If I can be completely honest, when I say I'm fine, what is the feeling underneath that word?" },
      { id: 310, t: "feelings", q: "If I can be completely honest, is there a version of me that is quietly furious — and what is that anger actually about?" },
      { id: 311, t: "feelings", q: "If I can be completely honest, do I give myself permission to feel bad without turning it into a productivity problem to solve?" },
      { id: 312, t: "feelings", q: "If I can be completely honest, what emotion am I most afraid other people will see in me?" },
      { id: 313, t: "feelings", q: "If I can be completely honest, have I ever felt relief when something ended that I had convinced myself I wanted?" },
      { id: 314, t: "feelings", q: "If I can be completely honest, what do I feel when a room goes quiet and I'm left alone with myself?" },
      { id: 315, t: "feelings", q: "If I can be completely honest, is there something I've been calling 'being strong' that is actually just refusing to feel?" },
      { id: 316, t: "feelings", q: "If I can be completely honest, what is the oldest feeling I carry — the one that was there before I had words for it?" },
      { id: 317, t: "feelings", q: "If I can be completely honest, have I ever felt like a burden to the people who love me — and did I ever tell anyone?" },
      { id: 318, t: "feelings", q: "If I can be completely honest, what feeling arises when I imagine truly succeeding at what I want most?" },
      { id: 319, t: "feelings", q: "If I can be completely honest, is there a sadness in me that has no specific cause — just a weight I've learned to carry?" },
      { id: 320, t: "feelings", q: "If I can be completely honest, do I know the difference between being calm and being numb?" },
      { id: 321, t: "feelings", q: "If I can be completely honest, what would happen if I stopped managing my feelings and just let one fully arrive?" },
      { id: 322, t: "feelings", q: "If I can be completely honest, is there something I feel ashamed of that, if I said it out loud, might finally lose its power over me?" },
      { id: 323, t: "feelings", q: "If I can be completely honest, what feeling do I associate with home — and does where I live now give me that?" },
      { id: 324, t: "feelings", q: "If I can be completely honest, when was the last time I cried — and did I allow it fully, or did I stop it halfway?" },
      { id: 325, t: "feelings", q: "If I can be completely honest, is there a feeling I only let myself have in private that I wish I could share?" },
      { id: 326, t: "feelings", q: "If I can be completely honest, what do I feel when I think about my childhood self — and does that child feel seen by who I've become?" },
      { id: 327, t: "feelings", q: "If I can be completely honest, what emotion appears most in my dreams — and what might it be trying to say?" },
      { id: 328, t: "feelings", q: "If I can be completely honest, have I been treating hope like a danger — bracing against it instead of leaning into it?" },
      { id: 329, t: "feelings", q: "If I can be completely honest, what is the difference between the feelings I show in public and the feelings I have at 3am?" },
      { id: 330, t: "feelings", q: "If I can be completely honest, is there a moment of tenderness toward myself I've been withholding — and what would it take to finally offer it?" },
      { id: 331, t: "feelings", q: "If I can be completely honest, what does disappointment do to me — do I turn it inward, outward, or do I pretend it isn't there?" },
      { id: 332, t: "feelings", q: "If I can be completely honest, have I been more loyal to feeling safe than to feeling alive?" },
      { id: 333, t: "feelings", q: "If I can be completely honest, what is the feeling I most want someone to name for me without me having to explain it?" },
      { id: 334, t: "feelings", q: "If I can be completely honest, do I believe my feelings are valid — or do I always need a reason to justify having them?" },
      { id: 335, t: "feelings", q: "If I can be completely honest, is there a version of happiness I've talked myself out of because it seemed too fragile to trust?" },
      { id: 336, t: "feelings", q: "If I can be completely honest, what do I feel when I receive genuine praise — and why doesn't it usually land the way it should?" },
      { id: 337, t: "feelings", q: "If I can be completely honest, have I ever felt something so strongly that it frightened me — and what did I do with that feeling?" },
      { id: 338, t: "feelings", q: "If I can be completely honest, what recurring emotional tone defines my inner life right now — and is that the life I want to be living?" },
      { id: 339, t: "feelings", q: "If I can be completely honest, what do I feel when I think about the future — and how much of that feeling is mine versus inherited from people around me?" },
      { id: 340, t: "feelings", q: "If I can be completely honest, is there grief underneath my anger — something I lost that I've been too proud or too tired to mourn?" },
      { id: 341, t: "feelings", q: "If I can be completely honest, what feeling do I wish I could feel more freely — and what do I believe is stopping me?" },
      { id: 342, t: "feelings", q: "If I can be completely honest, have I been confusing emotional unavailability with emotional stability?" },
      { id: 343, t: "feelings", q: "If I can be completely honest, what is one thing I feel deeply but have never said to a single person?" },
      { id: 344, t: "feelings", q: "If I can be completely honest, do I know what peace feels like in my body — and when did I last feel it?" },
      { id: 345, t: "feelings", q: "If I can be completely honest, is there something I've been dreading that, if I felt it fully, might actually release me?" },
      { id: 346, t: "feelings", q: "If I can be completely honest, what does envy, when it shows up, reveal about what I actually want for my own life?" },
      { id: 347, t: "feelings", q: "If I can be completely honest, is there a part of me that is quietly desperate — and what does it need that it isn't getting?" },
      { id: 348, t: "feelings", q: "If I can be completely honest, have I been mistaking emotional exhaustion for laziness — and punishing myself for it?" },
      { id: 349, t: "feelings", q: "If I can be completely honest, what feeling visits me most on Sunday evenings — and what does it say about my relationship with my life?" },
      { id: 350, t: "feelings", q: "If I can be completely honest, what would I feel if I woke up tomorrow and nothing in my life had to change — just me?" },
      { id: 351, t: "feelings", q: "If I can be completely honest, is there a loss I've never let myself fully grieve because grieving it would mean admitting how much it mattered?" },
      { id: 352, t: "feelings", q: "If I can be completely honest, what do I feel when I am truly kind to myself — and why does it sometimes feel uncomfortable?" },
      { id: 353, t: "feelings", q: "If I can be completely honest, have I been performing okayness for so long that I've lost track of what's real underneath it?" },
      { id: 354, t: "feelings", q: "If I can be completely honest, is there a version of myself I'm afraid to feel grief for — someone I used to be who I haven't properly said goodbye to?" },
      { id: 355, t: "feelings", q: "If I can be completely honest, what does hope feel like in my chest right now — is it there, and if not, when did it leave?" },
      { id: 356, t: "feelings", q: "If I can be completely honest, do I know what my emotional baseline is — and is that baseline one I've chosen or one I've simply accepted?" },
      { id: 357, t: "feelings", q: "If I can be completely honest, what emotion do I reach for to feel in control — and what am I really trying to protect?" },
      { id: 358, t: "feelings", q: "If I can be completely honest, is there something tender in me that I've been keeping behind glass because I'm afraid it will break?" },
      { id: 359, t: "feelings", q: "If I can be completely honest, what does the gap between how I feel and how I appear say about the life I've built?" },
      { id: 360, t: "feelings", q: "If I can be completely honest, what would my emotional life look like if I allowed it to be exactly as complicated as it actually is?" },
      { id: 361, t: "relationships", q: "If I can be completely honest, which of my relationships has changed the most — and have I acknowledged how different it is from what it used to be?" },
      { id: 362, t: "relationships", q: "If I can be completely honest, do I show up differently for people depending on how much I think they need me — and is that fairness or control?" },
      { id: 363, t: "relationships", q: "If I can be completely honest, have I ever let someone take the blame for something that was at least partly my fault?" },
      { id: 364, t: "relationships", q: "If I can be completely honest, is there a relationship I've been coasting in — showing up physically but not really there?" },
      { id: 365, t: "relationships", q: "If I can be completely honest, what do I actually contribute to my closest friendships beyond showing up when it's convenient?" },
      { id: 366, t: "relationships", q: "If I can be completely honest, have I ever expected someone to meet a need I never told them I had — and held it against them when they didn't?" },
      { id: 367, t: "relationships", q: "If I can be completely honest, which relationship in my life is teaching me the most about myself right now?" },
      { id: 368, t: "relationships", q: "If I can be completely honest, is there a friendship I've outgrown that I'm holding onto out of guilt rather than genuine connection?" },
      { id: 369, t: "relationships", q: "If I can be completely honest, do I have at least one person in my life who knows the full truth about me — not the edited version?" },
      { id: 370, t: "relationships", q: "If I can be completely honest, have I been a fair witness to the people in my life — or do I see them through the lens of who they were to me, not who they are now?" },
      { id: 371, t: "relationships", q: "If I can be completely honest, what do I wish I could tell a parent that I've never found the right moment to say?" },
      { id: 372, t: "relationships", q: "If I can be completely honest, is there a sibling relationship I've never properly invested in — and do I regret it?" },
      { id: 373, t: "relationships", q: "If I can be completely honest, how do I behave when a friend succeeds at something I've been working toward — and am I proud of that behavior?" },
      { id: 374, t: "relationships", q: "If I can be completely honest, do I make it easy or difficult for people to tell me hard truths?" },
      { id: 375, t: "relationships", q: "If I can be completely honest, is there a person I've written off who deserved more patience than I gave them?" },
      { id: 376, t: "relationships", q: "If I can be completely honest, how do I treat people when I'm under pressure — and is that the version of me I want them to remember?" },
      { id: 377, t: "relationships", q: "If I can be completely honest, do I take up the right amount of space in my relationships — or do I either disappear or overwhelm?" },
      { id: 378, t: "relationships", q: "If I can be completely honest, have I ever needed a friend to fail slightly just so I could feel okay about where I was?" },
      { id: 379, t: "relationships", q: "If I can be completely honest, what do I want from my friendships that I've never articulated — even to myself?" },
      { id: 380, t: "relationships", q: "If I can be completely honest, is there someone in my life who gives far more than they receive from me — and am I taking steps to change that?" },
      { id: 381, t: "relationships", q: "If I can be completely honest, what does forgiveness look like in my closest relationships — do I actually forgive, or do I just stop mentioning it?" },
      { id: 382, t: "relationships", q: "If I can be completely honest, have I ever made someone feel small in a way I've never gone back to address?" },
      { id: 383, t: "relationships", q: "If I can be completely honest, which relationship in my life could I improve simply by showing up more fully — without changing anything else?" },
      { id: 384, t: "relationships", q: "If I can be completely honest, do I know how to ask for help — or do I wait until I'm desperate and then resent that no one noticed sooner?" },
      { id: 385, t: "relationships", q: "If I can be completely honest, have I been loyal to people who have long since stopped being loyal to me?" },
      { id: 386, t: "relationships", q: "If I can be completely honest, what is the most important thing I've learned about friendship that I had to learn the hard way?" },
      { id: 387, t: "relationships", q: "If I can be completely honest, is there a relationship I keep returning to even though it consistently makes me feel worse about myself?" },
      { id: 388, t: "relationships", q: "If I can be completely honest, what do my relationships reveal about how much I value myself?" },
      { id: 389, t: "relationships", q: "If I can be completely honest, have I been the person who pulls away first — and do I know why I do that?" },
      { id: 390, t: "relationships", q: "If I can be completely honest, who in my life do I most take for granted — and what would it take for me to stop?" },
      { id: 391, t: "relationships", q: "If I can be completely honest, is there a version of me that appears only in certain relationships — and is that version the truest?" },
      { id: 392, t: "relationships", q: "If I can be completely honest, have I ever ended a friendship without explanation — and does the other person deserve one, even now?" },
      { id: 393, t: "relationships", q: "If I can be completely honest, how do I show love to the people in my life — and is that actually how they feel loved?" },
      { id: 394, t: "relationships", q: "If I can be completely honest, what is the conversation I keep putting off with someone who matters to me?" },
      { id: 395, t: "relationships", q: "If I can be completely honest, is there a family dynamic I've been silently participating in that I should probably name out loud?" },
      { id: 396, t: "relationships", q: "If I can be completely honest, do I choose friends who challenge me or friends who confirm what I already believe?" },
      { id: 397, t: "relationships", q: "If I can be completely honest, what is the thing I most fear someone who knows me well will eventually realize about me?" },
      { id: 398, t: "relationships", q: "If I can be completely honest, have I confused proximity with intimacy — spending time with people I'm not actually close to?" },
      { id: 399, t: "relationships", q: "If I can be completely honest, what would my relationships look like if I stopped trying to be needed and started focusing on being present?" },
      { id: 400, t: "relationships", q: "If I can be completely honest, is there a relationship in my life I've been grieving quietly — a drifting apart I never fully acknowledged?" },
      { id: 401, t: "relationships", q: "If I can be completely honest, do I know how to repair a relationship after a rupture — or do I default to either pretending it didn't happen or walking away?" },
      { id: 402, t: "relationships", q: "If I can be completely honest, what does it mean that some of my closest relationships exist mostly in my head rather than in regular contact?" },
      { id: 403, t: "relationships", q: "If I can be completely honest, how many of my relationships are built on who I was ten years ago — and who would be here if they only met me now?" },
      { id: 404, t: "relationships", q: "If I can be completely honest, have I been available to the people who need me — or have I been too wrapped up in my own story to show up for theirs?" },
      { id: 405, t: "relationships", q: "If I can be completely honest, what do I need from my relationships that I haven't been honest enough to ask for?" },
      { id: 406, t: "relationships", q: "If I can be completely honest, is there someone whose opinion of me I've given far too much power over my sense of self?" },
      { id: 407, t: "relationships", q: "If I can be completely honest, when did I last tell someone in my life exactly how much they mean to me — not implied, but said directly?" },
      { id: 408, t: "relationships", q: "If I can be completely honest, do I let people love me the way they know how — or do I grade their effort against an invisible standard?" },
      { id: 409, t: "relationships", q: "If I can be completely honest, what relationship pattern did I inherit from my family that I haven't consciously decided to keep or release?" },
      { id: 410, t: "relationships", q: "If I can be completely honest, is there someone I've never properly thanked — whose presence in my life shaped me more than I've acknowledged?" },
      { id: 411, t: "relationships", q: "If I can be completely honest, do I know the difference between a relationship that's going through something hard and one that has quietly ended?" },
      { id: 412, t: "relationships", q: "If I can be completely honest, have I been the kind of friend to others that I would want for myself?" },
      { id: 413, t: "relationships", q: "If I can be completely honest, what does the quality of my closest relationships say about how I see myself?" },
      { id: 414, t: "relationships", q: "If I can be completely honest, is there a person I'd want back in my life if I had the courage to reach out — and what's actually stopping me?" },
      { id: 415, t: "relationships", q: "If I can be completely honest, what would my relationships look like if I brought the same honesty to them that I'm trying to bring to these pages?" },
      { id: 416, t: "life", q: "If I can be completely honest, what do I spend the most time on that contributes the least to the life I actually want?" },
      { id: 417, t: "life", q: "If I can be completely honest, is there a version of success I've been pursuing that isn't actually mine — one I inherited or absorbed from someone else?" },
      { id: 418, t: "life", q: "If I can be completely honest, what habit of mine is holding me in place — and why haven't I changed it despite knowing exactly what it costs me?" },
      { id: 419, t: "life", q: "If I can be completely honest, do I know what I actually believe — not what I've been taught to believe, but what I've arrived at on my own?" },
      { id: 420, t: "life", q: "If I can be completely honest, what would my daily life look like if I stopped performing productivity and started practicing presence?" },
      { id: 421, t: "life", q: "If I can be completely honest, is there a chapter of my life I've rewritten in memory to be less painful than it actually was?" },
      { id: 422, t: "life", q: "If I can be completely honest, what am I avoiding that, if I faced it, might completely change the direction of my life?" },
      { id: 423, t: "life", q: "If I can be completely honest, do I take care of my body the way I would take care of someone I deeply loved?" },
      { id: 424, t: "life", q: "If I can be completely honest, what have I given up on that I haven't admitted — even to myself?" },
      { id: 425, t: "life", q: "If I can be completely honest, what is the gap between the life I describe to others and the life I actually live each day?" },
      { id: 426, t: "life", q: "If I can be completely honest, what am I most grateful for that I almost never think about?" },
      { id: 427, t: "life", q: "If I can be completely honest, if I could change one decision I made in my twenties, what would it be — and have I made peace with it?" },
      { id: 428, t: "life", q: "If I can be completely honest, do I know what a meaningful day feels like for me — and when did I last have one?" },
      { id: 429, t: "life", q: "If I can be completely honest, is there a dream I've dismissed as impractical that I've never truly stopped wanting?" },
      { id: 430, t: "life", q: "If I can be completely honest, what does rest mean to me — do I allow it, or does doing nothing feel like failing?" },
      { id: 431, t: "life", q: "If I can be completely honest, what would I do with my days if no one was watching and nothing was being measured?" },
      { id: 432, t: "life", q: "If I can be completely honest, what has my relationship with money revealed about my relationship with security?" },
      { id: 433, t: "life", q: "If I can be completely honest, what expectation of myself am I carrying that is no longer useful — and who would I be without it?" },
      { id: 434, t: "life", q: "If I can be completely honest, when was the last time I did something purely for the joy of it — not to improve, not to share, not to achieve?" },
      { id: 435, t: "life", q: "If I can be completely honest, what does my morning routine reveal about how I actually feel about the day ahead?" },
      { id: 436, t: "life", q: "If I can be completely honest, is there a city, place, or life that I carry around as a fantasy of who I could have been?" },
      { id: 437, t: "life", q: "If I can be completely honest, what have I been calling self-care that is actually avoidance — and what would genuine self-care look like?" },
      { id: 438, t: "life", q: "If I can be completely honest, what talent or capacity in me has gone neglected — and do I know why I let it go?" },
      { id: 439, t: "life", q: "If I can be completely honest, what does the thing I most dread say about what I most value?" },
      { id: 440, t: "life", q: "If I can be completely honest, is there a version of my life that ended without a funeral — a path I left and never said goodbye to?" },
      { id: 441, t: "life", q: "If I can be completely honest, what is one thing about my past I've been too ashamed to be curious about?" },
      { id: 442, t: "life", q: "If I can be completely honest, what am I building — and is it something I actually want to live inside of, or something I'm building to prove a point?" },
      { id: 443, t: "life", q: "If I can be completely honest, do I move through the world with intention — or do I mostly react to what arrives?" },
      { id: 444, t: "life", q: "If I can be completely honest, what would I deeply regret if I found out I only had five years left to live?" },
      { id: 445, t: "life", q: "If I can be completely honest, is the life I'm living an expression of my values — or a performance of what I think a life should look like?" },
      { id: 446, t: "life", q: "If I can be completely honest, what would need to be true for me to feel like I'm enough — right now, as I am?" },
      { id: 447, t: "life", q: "If I can be completely honest, is there a belief about myself that has been quietly organizing my choices — and is it actually true?" },
      { id: 448, t: "life", q: "If I can be completely honest, what part of my childhood is still running my adult life?" },
      { id: 449, t: "life", q: "If I can be completely honest, what is the most important thing I've learned — the thing I wouldn't trade, even for an easier path?" },
      { id: 450, t: "life", q: "If I can be completely honest, do I know what I'm afraid of losing so much that I've organized my whole life around protecting it?" },
      { id: 451, t: "life", q: "If I can be completely honest, what does my relationship with time reveal about how I feel about my life?" },
      { id: 452, t: "life", q: "If I can be completely honest, is there a compliment I've received that I should have believed but dismissed — and why didn't I let it in?" },
      { id: 453, t: "life", q: "If I can be completely honest, what would I do differently if I knew no one from my past was watching or judging?" },
      { id: 454, t: "life", q: "If I can be completely honest, what does the way I spend my Sundays reveal about the life I'm actually living?" },
      { id: 455, t: "life", q: "If I can be completely honest, what has been the cost of my perfectionism — not the benefit, the actual cost?" },
      { id: 456, t: "life", q: "If I can be completely honest, is there an apology I owe to someone — including myself — that I've been withholding?" },
      { id: 457, t: "life", q: "If I can be completely honest, what chapter of my life am I in right now — and do I know what this chapter is trying to teach me?" },
      { id: 458, t: "life", q: "If I can be completely honest, what would I think of my current self if I could meet them from ten years ago?" },
      { id: 459, t: "life", q: "If I can be completely honest, when was the last time I was genuinely surprised by life — and how do I feel about how rare that has become?" },
      { id: 460, t: "life", q: "If I can be completely honest, what is the most honest sentence I can write about who I am right now?" },
      { id: 461, t: "life", q: "If I can be completely honest, what do I wish someone had told me earlier that I had to learn the hard way?" },
      { id: 462, t: "life", q: "If I can be completely honest, is there a part of my identity I've been holding onto that no longer fits who I'm becoming?" },
      { id: 463, t: "life", q: "If I can be completely honest, what is the one thing I keep saying I'll do when conditions are right — and what would happen if I started now?" },
      { id: 464, t: "life", q: "If I can be completely honest, what does my inner critic say most often — and is there any part of it I'm ready to stop believing?" },
      { id: 465, t: "life", q: "If I can be completely honest, what does living well mean to me — and how far is my daily life from that definition?" },
      { id: 466, t: "life", q: "If I can be completely honest, what have I been calling a phase that has actually become the pattern?" },
      { id: 467, t: "life", q: "If I can be completely honest, who am I when no one needs anything from me — and do I like that person?" },
      { id: 468, t: "life", q: "If I can be completely honest, what is the bravest thing I've ever done — and have I given myself proper credit for it?" },
      { id: 469, t: "life", q: "If I can be completely honest, what would I want written about me — not on a tombstone, but in the honest account of someone who really knew me?" },
      { id: 470, t: "life", q: "If I can be completely honest, if this journal entry were the last thing I ever wrote, what is the one truth I would want to leave behind?" },
      { id: 471, t: "love", q: "If I can be completely honest, what is the most generous interpretation of someone who broke my heart — and can I hold that alongside my own hurt?" },
      { id: 472, t: "love", q: "If I can be completely honest, have I ever loved someone quietly from a distance rather than risk being rejected up close?" },
      { id: 473, t: "love", q: "If I can be completely honest, what does it mean that some of my most vivid memories are of moments of connection — not achievements?" },
      { id: 474, t: "love", q: "If I can be completely honest, what kind of partner do I become when I feel secure — and is that who I want to be more of?" },
      { id: 475, t: "love", q: "If I can be completely honest, do I stay curious about the person I love — or have I stopped asking questions because I think I already know them?" },
      { id: 476, t: "love", q: "If I can be completely honest, have I ever convinced myself I was over someone only to realize the feeling had just gone underground?" },
      { id: 477, t: "love", q: "If I can be completely honest, what is the most honest thing I could say about what I'm looking for when I say I want love?" },
      { id: 478, t: "love", q: "If I can be completely honest, how do I show up in love when I'm tired, stressed, or depleted — and is that someone I'd want to be loved by?" },
      { id: 479, t: "love", q: "If I can be completely honest, have I been withholding tenderness from someone who needed it because I was too proud or too scared?" },
      { id: 480, t: "love", q: "If I can be completely honest, is there a version of love I've witnessed in others that made me quietly ache for it — and have I ever tried to build it?" },
      { id: 481, t: "love", q: "If I can be completely honest, what does commitment mean to me — not the ceremony or the label, but the actual daily choosing?" },
      { id: 482, t: "love", q: "If I can be completely honest, have I ever used humor, sarcasm, or busyness to avoid being emotionally available to someone who loved me?" },
      { id: 483, t: "love", q: "If I can be completely honest, what would I want someone who loved me to understand about me that I've never been able to say directly?" },
      { id: 484, t: "love", q: "If I can be completely honest, is there a relationship that changed me in a way I'm still discovering — and have I thanked it, even silently?" },
      { id: 485, t: "love", q: "If I can be completely honest, what does the way I say goodbye reveal about how afraid I am of being left?" },
      { id: 486, t: "love", q: "If I can be completely honest, do I believe I am capable of the kind of love I most want to receive?" },
      { id: 487, t: "love", q: "If I can be completely honest, have I ever loved someone in a way that diminished them — even with good intentions?" },
      { id: 488, t: "love", q: "If I can be completely honest, what is the love I've given that I'm most proud of — the kind no one saw and no one rewarded?" },
      { id: 489, t: "love", q: "If I can be completely honest, do I let love in slowly because I'm thoughtful — or because I'm afraid of how much I could lose?" },
      { id: 490, t: "love", q: "If I can be completely honest, what does the word 'home' mean to me when it comes to love — and have I ever found it?" },
      { id: 491, t: "love", q: "If I can be completely honest, have I ever needed someone to love me back as proof that I was worth loving — and what did it cost me when they couldn't?" },
      { id: 492, t: "love", q: "If I can be completely honest, what quality in a partner have I undervalued because it wasn't exciting — only to miss it deeply later?" },
      { id: 493, t: "love", q: "If I can be completely honest, is there a relationship I sabotaged without fully understanding why — and do I understand it now?" },
      { id: 494, t: "love", q: "If I can be completely honest, what does it mean to love someone well when loving them is inconvenient?" },
      { id: 495, t: "love", q: "If I can be completely honest, do I know how to be alone in a way that makes me better at being together?" },
      { id: 496, t: "love", q: "If I can be completely honest, what is the most important thing love has taught me about who I am?" },
      { id: 497, t: "love", q: "If I can be completely honest, have I been searching for a feeling in love that actually lives inside me — waiting for permission to emerge?" },
      { id: 498, t: "love", q: "If I can be completely honest, what would change about the way I love if I truly believed I wouldn't be abandoned for showing my whole self?" },
      { id: 499, t: "love", q: "If I can be completely honest, is there something I've never asked for in love because I decided, somewhere along the way, that it was too much to want?" },
      { id: 500, t: "love", q: "If I can be completely honest, what is the truest thing I know about love — not what I've read or been told, but what I've actually lived?" },
    ];

    const LABELS = {
      love: 'Love',
      feelings: 'Feelings',
      relationships: 'Relationships',
      life: 'Life',
      custom: 'My Questions'
    };

    const COLORS = {
      love: 'var(--love)',
      feelings: 'var(--feelings)',
      relationships: 'var(--rels)',
      life: 'var(--life)',
      custom: 'var(--custom)'
    };